// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NigdeTerminal.App.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NigdeTerminal.App.Data.Migrations
{
    [DbContext(typeof(NigdeTerminalDbContext))]
    [Migration("20260831115058_SplitExitDepartureDateAndTime")]
    partial class SplitExitDepartureDateAndTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NigdeTerminal.App.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanDepartFromCenter")
                        .HasColumnType("boolean")
                        .HasColumnName("merkez_cikis_yapabilir");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firma_turu");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("firmalar", null, t =>
                        {
                            t.HasCheckConstraint("ck_firmalar_firma_turu", "firma_turu IN ('Sehirlerarasi', 'YerelMinibus')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e01"),
                            CanDepartFromCenter = false,
                            CompanyType = "YerelMinibus",
                            IsActive = true,
                            Name = "AKSARAY BİRLİK"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e02"),
                            CanDepartFromCenter = false,
                            CompanyType = "YerelMinibus",
                            IsActive = true,
                            Name = "DERİNKUYU"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e03"),
                            CanDepartFromCenter = false,
                            CompanyType = "YerelMinibus",
                            IsActive = true,
                            Name = "KARACAERLER"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e04"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "NİĞDE AYDOĞANLAR SEYAHAT"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e05"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "NİĞDE İNAN TURİZM"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e06"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "LÜKS EREĞLİ"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e07"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "NET TURİZM SEYAHAT"
                        });
                });

            modelBuilder.Entity("NigdeTerminal.App.Models.ExitRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("firma_id");

                    b.Property<bool>("DepartedFromCenter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("merkezden_cikti_mi");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("cikis_tarihi");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("cikis_saati");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("odeme_yontemi");

                    b.Property<decimal>("TariffAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tarife_ucreti");

                    b.Property<string>("TariffName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tarife_adi");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plaka");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartureDate", "DepartureTime");

                    b.ToTable("cikis_kayitlari", null, t =>
                        {
                            t.HasCheckConstraint("ck_cikis_kayitlari_odeme_yontemi", "odeme_yontemi IN ('Nakit', 'KrediKarti')");

                            t.HasCheckConstraint("ck_cikis_kayitlari_tarife_ucreti", "tarife_ucreti >= 0");
                        });
                });

            modelBuilder.Entity("NigdeTerminal.App.Models.ExitRecord", b =>
                {
                    b.HasOne("NigdeTerminal.App.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
