// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NigdeTerminal.App.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NigdeTerminal.App.Data.Migrations
{
    [DbContext(typeof(NigdeTerminalDbContext))]
    [Migration("20260829090859_SeedInitialCompanies")]
    partial class SeedInitialCompanies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NigdeTerminal.App.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanDepartFromCenter")
                        .HasColumnType("boolean")
                        .HasColumnName("merkez_cikis_yapabilir");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firma_turu");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("firmalar", null, t =>
                        {
                            t.HasCheckConstraint("ck_firmalar_firma_turu", "firma_turu IN ('Sehirlerarasi', 'YerelMinibus')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e01"),
                            CanDepartFromCenter = false,
                            CompanyType = "YerelMinibus",
                            IsActive = true,
                            Name = "Aksaray"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e02"),
                            CanDepartFromCenter = false,
                            CompanyType = "YerelMinibus",
                            IsActive = true,
                            Name = "Derinkuyu"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e03"),
                            CanDepartFromCenter = false,
                            CompanyType = "YerelMinibus",
                            IsActive = true,
                            Name = "Karacaerler"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e04"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "Aydoğanlar"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e05"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "İnan"
                        },
                        new
                        {
                            Id = new Guid("5aa15e8f-faf7-4bf3-a259-09e4433a5e06"),
                            CanDepartFromCenter = true,
                            CompanyType = "Sehirlerarasi",
                            IsActive = true,
                            Name = "Lüks Ereğli"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
